"""Add UserMeta model

Revision ID: 9322b8b703dd
Revises: 005_dataset_meta
Create Date: 2026-02-03 08:35:32.569164+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9322b8b703dd'
down_revision: Union[str, None] = '005_dataset_meta'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('telegram_url', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_image', sa.String(length=500), nullable=True),
    sa.Column('ball', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_user_meta_ball'), 'user_meta', ['ball'], unique=False)
    op.create_index(op.f('ix_user_meta_id'), 'user_meta', ['id'], unique=False)
    op.create_index(op.f('ix_user_meta_user_id'), 'user_meta', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_meta_user_id'), table_name='user_meta')
    op.drop_index(op.f('ix_user_meta_id'), table_name='user_meta')
    op.drop_index(op.f('ix_user_meta_ball'), table_name='user_meta')
    op.drop_table('user_meta')
    # ### end Alembic commands ###
